const mongoose = require('mongoose');

const LearningRoadmapSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    unique: true
  },
  targetRole: {
    type: String,
    default: 'Software Engineer'
  },
  summary: {
    type: String,
    default: 'Personalized 4-week study plan generated by AI based on mock interview performance.'
  },
  overallProgress: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  weeks: [{
    weekNumber: { type: Number, required: true },
    title: { type: String, required: true },
    topic: { type: String, required: true },
    focusArea: { type: String, required: true },
    reason: { type: String, required: true },
    keyConcepts: [{ type: String }],
    estimatedHours: { type: Number, default: 3 },
    practiceQuestionsCount: { type: Number, default: 5 },
    completed: { type: Boolean, default: false },
    subtasksCompleted: [{ type: String }] // List of completed keyConcept strings
  }],
  generatedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

module.exports = mongoose.model('LearningRoadmap', LearningRoadmapSchema);
